//go:build go1.22

// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/luikyv/mock-insurer/internal/api"
	"github.com/luikyv/mock-insurer/internal/insurer"
	"github.com/luikyv/mock-insurer/internal/timeutil"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	OAuth2SecurityScopes = "OAuth2Security.Scopes"
	OpenIdScopes         = "OpenId.Scopes"
)

// Defines values for InsuranceFinancialAssistanceCounterInstallmentsPeriodicity.
const (
	ANUAL         InsuranceFinancialAssistanceCounterInstallmentsPeriodicity = "ANUAL"
	BIMESTRAL     InsuranceFinancialAssistanceCounterInstallmentsPeriodicity = "BIMESTRAL"
	MENSAL        InsuranceFinancialAssistanceCounterInstallmentsPeriodicity = "MENSAL"
	QUADRIMESTRAL InsuranceFinancialAssistanceCounterInstallmentsPeriodicity = "QUADRIMESTRAL"
	SEMESTRAL     InsuranceFinancialAssistanceCounterInstallmentsPeriodicity = "SEMESTRAL"
	TRIMESTRAL    InsuranceFinancialAssistanceCounterInstallmentsPeriodicity = "TRIMESTRAL"
)

// Defines values for InsuranceFinancialAssistanceInsuredDocumentType.
const (
	CNPJ       InsuranceFinancialAssistanceInsuredDocumentType = "CNPJ"
	CPF        InsuranceFinancialAssistanceInsuredDocumentType = "CPF"
	OUTROS     InsuranceFinancialAssistanceInsuredDocumentType = "OUTROS"
	PASSAPORTE InsuranceFinancialAssistanceInsuredDocumentType = "PASSAPORTE"
)

// AmountDetails Detalhes de valores/limites
type AmountDetails = insurer.AmountDetails

// InsuranceFinancialAssistanceContractInfo defines model for InsuranceFinancialAssistanceContractInfo.
type InsuranceFinancialAssistanceContractInfo struct {
	// AcquittanceDate Data da Quitação Antecipada (quando houver)
	AcquittanceDate *timeutil.BrazilDate `json:"acquittanceDate,omitempty"`

	// AcquittanceValue Valor Quitação Antecipada (quando houver) - Valor Bruto
	AcquittanceValue *AmountDetails `json:"acquittanceValue,omitempty"`

	// AdministrativeFeesValue Valor da tarifa administrativa
	AdministrativeFeesValue AmountDetails `json:"administrativeFeesValue"`

	// AmortizationPeriod Prazo de Amortização do Saldo Devedor em meses
	AmortizationPeriod int `json:"amortizationPeriod"`

	// CertificateID Identificação do certificado de participante ou certificado individual ou apólice individual
	CertificateID string `json:"certificateId"`

	// ConceivedCreditValue Valor do Crédito concedido
	ConceivedCreditValue AmountDetails `json:"conceivedCreditValue"`

	// ContractID Identificador do contrato de assistência financeira
	ContractID string `json:"contractId"`

	// CounterInstallments Informações das contraprestações do contrato
	CounterInstallments InsuranceFinancialAssistanceCounterInstallments `json:"counterInstallments"`

	// CreditedLiquidValue Valor Líquido Creditado
	CreditedLiquidValue AmountDetails `json:"creditedLiquidValue"`

	// EffectiveCostRate Taxa do custo efetivo total
	EffectiveCostRate AmountDetails `json:"effectiveCostRate"`

	// ExpensesValue Valor de Despesas e Encargos (quando houver) - Valor de Despesas e Encargos de juros (moratórios)
	ExpensesValue *AmountDetails `json:"expensesValue,omitempty"`

	// FinesValue Valor de Multa (quando houver)
	FinesValue *AmountDetails `json:"finesValue,omitempty"`

	// GroupContractID Identificação do contrato ou apólice (Quando contratação coletiva)
	GroupContractID *string                               `json:"groupContractId,omitempty"`
	Insureds        []InsuranceFinancialAssistanceInsured `json:"insureds"`

	// InterestRate Taxa de juros contratada
	InterestRate AmountDetails `json:"interestRate"`

	// InterestValue Valor de juros - Os juros informados neste campo são remuneratórios
	InterestValue AmountDetails `json:"interestValue"`

	// MonetaryUpdatesValue Valor de Atualização Monetária (quando houver) - Valor de Atualização Monetária referentes a cada prestação, se houver
	MonetaryUpdatesValue *AmountDetails `json:"monetaryUpdatesValue,omitempty"`

	// SusepProcessNumber Identificação do processo Susep referente ao plano que está vinculado o contrato de assistência financeira
	SusepProcessNumber string `json:"susepProcessNumber"`

	// TaxesValue Valor de Tributos - Valor total de Tributos incidentes sobre a operação
	TaxesValue AmountDetails `json:"taxesValue"`
}

// InsuranceFinancialAssistanceCounterInstallments Informações das contraprestações do contrato
type InsuranceFinancialAssistanceCounterInstallments struct {
	// FirstDate Data de vencimento da primeira contraprestação
	FirstDate timeutil.BrazilDate `json:"firstDate"`

	// LastDate Data de vencimento da última contraprestação
	LastDate timeutil.BrazilDate `json:"lastDate"`

	// Periodicity Periodicidade das contraprestações
	Periodicity InsuranceFinancialAssistanceCounterInstallmentsPeriodicity `json:"periodicity"`

	// Quantity Quantidade das contraprestações
	Quantity int `json:"quantity"`

	// Value Detalhes de valores/limites
	Value AmountDetails `json:"value"`
}

// InsuranceFinancialAssistanceCounterInstallmentsPeriodicity Periodicidade das contraprestações
type InsuranceFinancialAssistanceCounterInstallmentsPeriodicity string

// InsuranceFinancialAssistanceInsured Informações do segurado/participante
type InsuranceFinancialAssistanceInsured struct {
	// DocumentNumber Documento de identificação do Segurado / Participante associado à apólice
	DocumentNumber string `json:"documentNumber"`

	// DocumentType Tipo de Documento do Segurado / Participante
	DocumentType InsuranceFinancialAssistanceInsuredDocumentType `json:"documentType"`

	// DocumentTypeOthers Informar o documento quando for do tipo Outros
	DocumentTypeOthers *string `json:"documentTypeOthers,omitempty"`

	// Name Nome ou Razão Social do Segurado / Participante
	Name string `json:"name"`
}

// InsuranceFinancialAssistanceInsuredDocumentType Tipo de Documento do Segurado / Participante
type InsuranceFinancialAssistanceInsuredDocumentType string

// InsuranceFinancialAssistanceMovements defines model for InsuranceFinancialAssistanceMovements.
type InsuranceFinancialAssistanceMovements struct {
	// LifePensionPmBacAmount Saldo individual da PMBaC sobrevivência (quando houver - Obrigatório se o produto for de Sobrevivência) - Declara o Saldo individual da PMBaC sobrevivência ao final do mês.
	LifePensionPmBacAmount *AmountDetails `json:"lifePensionPmBacAmount,omitempty"`

	// PensionPlanPmBacAmount Saldo individual da PMBaC risco (quando houver - Obrigatório se o produto for de Risco estruturado no regime de Capitalização) - Declara o Saldo individual da PMBaC de risco ao final do mês
	PensionPlanPmBacAmount *AmountDetails `json:"pensionPlanPmBacAmount,omitempty"`

	// RemainingCounterInstallmentsQuantity Quantidade de contraprestações a vencer
	RemainingCounterInstallmentsQuantity int `json:"remainingCounterInstallmentsQuantity"`

	// RemainingUnpaidCounterInstallmentsQuantity Quantidade de Contraprestações vencidas e não pagas integralmente. Considerar valor "0" quando não houver contraprestações vencidas
	RemainingUnpaidCounterInstallmentsQuantity int `json:"remainingUnpaidCounterInstallmentsQuantity"`

	// UpdatedDebitAmount Saldo Devedor Atualizado - Saldo devedor na data do movimento
	UpdatedDebitAmount AmountDetails `json:"updatedDebitAmount"`
}

// ResponseError defines model for ResponseError.
type ResponseError struct {
	Errors []struct {
		// Code Código de erro específico do endpoint
		Code string `json:"code"`

		// Detail Descrição legível por humanos deste erro específico
		Detail string `json:"detail"`

		// RequestDateTime Data e hora da consulta, conforme especificação RFC-3339, formato UTC.
		RequestDateTime *timeutil.DateTime `json:"requestDateTime,omitempty"`

		// Title Título legível por humanos deste erro específico
		Title string `json:"title"`
	} `json:"errors"`
	Meta *api.Meta `json:"meta,omitempty"`
}

// ResponseInsuranceFinancialAssistance defines model for ResponseInsuranceFinancialAssistance.
type ResponseInsuranceFinancialAssistance struct {
	Data []struct {
		// Brand Marca reportada pelo participante do Open Insurance. O conceito a que se refere a marca é em essência uma promessa das sociedades sob ela em fornecer uma série específica de atributos, benefícios e serviços uniformes aos clientes.
		Brand struct {
			Companies []struct {
				// CnpjNumber CNPJ da sociedade pertencente à marca
				CnpjNumber string `json:"cnpjNumber"`

				// CompanyName Nome da sociedade pertencente à marca
				CompanyName string `json:"companyName"`
				Contracts   *[]struct {
					// ContractID Identificador do contrato de assistência financeira
					ContractID string `json:"contractId"`
				} `json:"contracts,omitempty"`
			} `json:"companies"`

			// Name Marca reportada pelo participante do Open Insurance. O conceito a que se refere a marca é em essência uma promessa das sociedades sob ela em fornecer uma série específica de atributos, benefícios e serviços uniformes aos clientes.
			Name string `json:"name"`
		} `json:"brand"`
	} `json:"data"`
	Links api.Links `json:"links"`
	Meta  api.Meta  `json:"meta"`
}

// ResponseInsuranceFinancialAssistanceContractInfo defines model for ResponseInsuranceFinancialAssistanceContractInfo.
type ResponseInsuranceFinancialAssistanceContractInfo struct {
	Data  InsuranceFinancialAssistanceContractInfo `json:"data"`
	Links api.Links                                `json:"links"`
	Meta  api.Meta                                 `json:"meta"`
}

// ResponseInsuranceFinancialAssistanceMovements defines model for ResponseInsuranceFinancialAssistanceMovements.
type ResponseInsuranceFinancialAssistanceMovements struct {
	Data  []InsuranceFinancialAssistanceMovements `json:"data"`
	Links api.Links                               `json:"links"`
	Meta  api.Meta                                `json:"meta"`
}

// Authorization defines model for Authorization.
type Authorization = string

// ContractID defines model for contractId.
type ContractID = string

// Page defines model for page.
type Page = int32

// PageSize defines model for pageSize.
type PageSize = int32

// XMinV defines model for x-min-v.
type XMinV = string

// XVHeader defines model for x-v.
type XVHeader = string

// XCustomerUserAgent defines model for xCustomerUserAgent.
type XCustomerUserAgent = string

// XFapiAuthDate defines model for xFapiAuthDate.
type XFapiAuthDate = string

// XFapiCustomerIPAddress defines model for xFapiCustomerIpAddress.
type XFapiCustomerIPAddress = string

// XFapiInteractionID defines model for xFapiInteractionId.
type XFapiInteractionID = string

// BadRequest defines model for BadRequest.
type BadRequest = ResponseError

// Forbidden defines model for Forbidden.
type Forbidden = ResponseError

// InternalServerError defines model for InternalServerError.
type InternalServerError = ResponseError

// MethodNotAllowed defines model for MethodNotAllowed.
type MethodNotAllowed = ResponseError

// NotAcceptable defines model for NotAcceptable.
type NotAcceptable = ResponseError

// NotFound defines model for NotFound.
type NotFound = ResponseError

// OKResponseInsuranceFinancialAssistance defines model for OKResponseInsuranceFinancialAssistance.
type OKResponseInsuranceFinancialAssistance = ResponseInsuranceFinancialAssistance

// OKResponseInsuranceFinancialAssistanceContractInfo defines model for OKResponseInsuranceFinancialAssistanceContractInfo.
type OKResponseInsuranceFinancialAssistanceContractInfo = ResponseInsuranceFinancialAssistanceContractInfo

// OKResponseInsuranceFinancialAssistanceMovements defines model for OKResponseInsuranceFinancialAssistanceMovements.
type OKResponseInsuranceFinancialAssistanceMovements = ResponseInsuranceFinancialAssistanceMovements

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = ResponseError

// Unauthorized defines model for Unauthorized.
type Unauthorized = ResponseError

// UnprocessableEntity defines model for UnprocessableEntity.
type UnprocessableEntity = ResponseError

// GetInsuranceFinancialAssistanceParams defines parameters for GetInsuranceFinancialAssistance.
type GetInsuranceFinancialAssistanceParams struct {
	// Page Número da página que está sendo requisitada (o valor da primeira página é 1).
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Quantidade total de registros por páginas.
	PageSize *PageSize `form:"page-size,omitempty" json:"page-size,omitempty"`

	// Authorization Cabeçalho HTTP padrão. Permite que as credenciais sejam fornecidas dependendo do tipo de recurso solicitado.
	Authorization Authorization `json:"Authorization"`

	// XFapiAuthDate Data em que o usuário logou pela última vez com o receptor. Representada de acordo com a [RFC7231](https://tools.ietf.org/html/rfc7231). Exemplo: Sun, 10 Sep 2017 19:43:31 UTC
	XFapiAuthDate *XFapiAuthDate `json:"x-fapi-auth-date,omitempty"`

	// XFapiCustomerIPAddress O endereço IP do usuário se estiver atualmente logado com o receptor.
	XFapiCustomerIPAddress *XFapiCustomerIPAddress `json:"x-fapi-customer-ip-address,omitempty"`

	// XFapiInteractionID Um UID [RFC4122](https://tools.ietf.org/html/rfc4122) usado como um ID de correlação. Se fornecido, o transmissor deve "reproduzir" esse valor no cabeçalho de resposta.
	XFapiInteractionID XFapiInteractionID `json:"x-fapi-interaction-id"`

	// XCustomerUserAgent Indica o user-agent que o usuário utiliza.
	XCustomerUserAgent *XCustomerUserAgent `json:"x-customer-user-agent,omitempty"`

	// XVHeader Versão do endpoint da API requisitado pelo cliente. O titular dos dados deve
	// responder com a versão mais alta suportada entre x-min-v e x-v. Se o valor de
	// x-min-v for igual ou maior que o valor de x-v, o cabeçalho x-min-v deve ser
	// tratado como ausente. Se todas as versões solicitadas não forem suportadas,
	// o titular dos dados deve responder com o código de status 406 Not Acceptable.
	XVHeader *XVHeader `json:"x-v,omitempty"`

	// XMinV Versão mínima do endpoint da API requisitado pelo cliente. O detentor dos dados
	// deve responder com a versão mais alta suportada entre x-min-v e x-v. Se todas as
	// versões solicitadas não forem suportadas, o titular dos dados deve responder com
	// um código de status 406 Not Acceptable.
	XMinV *XMinV `json:"x-min-v,omitempty"`
}

// GetInsuranceFinancialAssistanceContractInfoParams defines parameters for GetInsuranceFinancialAssistanceContractInfo.
type GetInsuranceFinancialAssistanceContractInfoParams struct {
	// Authorization Cabeçalho HTTP padrão. Permite que as credenciais sejam fornecidas dependendo do tipo de recurso solicitado.
	Authorization Authorization `json:"Authorization"`

	// XFapiAuthDate Data em que o usuário logou pela última vez com o receptor. Representada de acordo com a [RFC7231](https://tools.ietf.org/html/rfc7231). Exemplo: Sun, 10 Sep 2017 19:43:31 UTC
	XFapiAuthDate *XFapiAuthDate `json:"x-fapi-auth-date,omitempty"`

	// XFapiCustomerIPAddress O endereço IP do usuário se estiver atualmente logado com o receptor.
	XFapiCustomerIPAddress *XFapiCustomerIPAddress `json:"x-fapi-customer-ip-address,omitempty"`

	// XFapiInteractionID Um UID [RFC4122](https://tools.ietf.org/html/rfc4122) usado como um ID de correlação. Se fornecido, o transmissor deve "reproduzir" esse valor no cabeçalho de resposta.
	XFapiInteractionID XFapiInteractionID `json:"x-fapi-interaction-id"`

	// XCustomerUserAgent Indica o user-agent que o usuário utiliza.
	XCustomerUserAgent *XCustomerUserAgent `json:"x-customer-user-agent,omitempty"`

	// XVHeader Versão do endpoint da API requisitado pelo cliente. O titular dos dados deve
	// responder com a versão mais alta suportada entre x-min-v e x-v. Se o valor de
	// x-min-v for igual ou maior que o valor de x-v, o cabeçalho x-min-v deve ser
	// tratado como ausente. Se todas as versões solicitadas não forem suportadas,
	// o titular dos dados deve responder com o código de status 406 Not Acceptable.
	XVHeader *XVHeader `json:"x-v,omitempty"`

	// XMinV Versão mínima do endpoint da API requisitado pelo cliente. O detentor dos dados
	// deve responder com a versão mais alta suportada entre x-min-v e x-v. Se todas as
	// versões solicitadas não forem suportadas, o titular dos dados deve responder com
	// um código de status 406 Not Acceptable.
	XMinV *XMinV `json:"x-min-v,omitempty"`
}

// GetInsuranceFinancialAssistanceMovementsParams defines parameters for GetInsuranceFinancialAssistanceMovements.
type GetInsuranceFinancialAssistanceMovementsParams struct {
	// Page Número da página que está sendo requisitada (o valor da primeira página é 1).
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// PageSize Quantidade total de registros por páginas.
	PageSize *PageSize `form:"page-size,omitempty" json:"page-size,omitempty"`

	// Authorization Cabeçalho HTTP padrão. Permite que as credenciais sejam fornecidas dependendo do tipo de recurso solicitado.
	Authorization Authorization `json:"Authorization"`

	// XFapiAuthDate Data em que o usuário logou pela última vez com o receptor. Representada de acordo com a [RFC7231](https://tools.ietf.org/html/rfc7231). Exemplo: Sun, 10 Sep 2017 19:43:31 UTC
	XFapiAuthDate *XFapiAuthDate `json:"x-fapi-auth-date,omitempty"`

	// XFapiCustomerIPAddress O endereço IP do usuário se estiver atualmente logado com o receptor.
	XFapiCustomerIPAddress *XFapiCustomerIPAddress `json:"x-fapi-customer-ip-address,omitempty"`

	// XFapiInteractionID Um UID [RFC4122](https://tools.ietf.org/html/rfc4122) usado como um ID de correlação. Se fornecido, o transmissor deve "reproduzir" esse valor no cabeçalho de resposta.
	XFapiInteractionID XFapiInteractionID `json:"x-fapi-interaction-id"`

	// XCustomerUserAgent Indica o user-agent que o usuário utiliza.
	XCustomerUserAgent *XCustomerUserAgent `json:"x-customer-user-agent,omitempty"`

	// XVHeader Versão do endpoint da API requisitado pelo cliente. O titular dos dados deve
	// responder com a versão mais alta suportada entre x-min-v e x-v. Se o valor de
	// x-min-v for igual ou maior que o valor de x-v, o cabeçalho x-min-v deve ser
	// tratado como ausente. Se todas as versões solicitadas não forem suportadas,
	// o titular dos dados deve responder com o código de status 406 Not Acceptable.
	XVHeader *XVHeader `json:"x-v,omitempty"`

	// XMinV Versão mínima do endpoint da API requisitado pelo cliente. O detentor dos dados
	// deve responder com a versão mais alta suportada entre x-min-v e x-v. Se todas as
	// versões solicitadas não forem suportadas, o titular dos dados deve responder com
	// um código de status 406 Not Acceptable.
	XMinV *XMinV `json:"x-min-v,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Obtem a lista de identificação de InsuranceFinancialAssistance
	// (GET /insurance-financial-assistance/contracts)
	GetInsuranceFinancialAssistance(w http.ResponseWriter, r *http.Request, params GetInsuranceFinancialAssistanceParams)
	// Obtém as informações gerais do contrato identificado por {contractId}
	// (GET /insurance-financial-assistance/{contractId}/contract-info)
	GetInsuranceFinancialAssistanceContractInfo(w http.ResponseWriter, r *http.Request, contractID ContractID, params GetInsuranceFinancialAssistanceContractInfoParams)
	// Obtém os dados de movimentação do contrato identificado por {contractId}
	// (GET /insurance-financial-assistance/{contractId}/movements)
	GetInsuranceFinancialAssistanceMovements(w http.ResponseWriter, r *http.Request, contractID ContractID, params GetInsuranceFinancialAssistanceMovementsParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetInsuranceFinancialAssistance operation middleware
func (siw *ServerInterfaceWrapper) GetInsuranceFinancialAssistance(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, OAuth2SecurityScopes, []string{"consent:consentId", "insurance-financial-assistance"})

	ctx = context.WithValue(ctx, OpenIdScopes, []string{"openid"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetInsuranceFinancialAssistanceParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "page-size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page-size", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page-size", Err: err})
		return
	}

	headers := r.Header

	// ------------- Required header parameter "Authorization" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authorization")]; found {
		var Authorization Authorization
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Authorization", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authorization", valueList[0], &Authorization, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Authorization", Err: err})
			return
		}

		params.Authorization = Authorization

	} else {
		err := fmt.Errorf("Header parameter Authorization is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Authorization", Err: err})
		return
	}

	// ------------- Optional header parameter "x-fapi-auth-date" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-fapi-auth-date")]; found {
		var XFapiAuthDate XFapiAuthDate
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "x-fapi-auth-date", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-fapi-auth-date", valueList[0], &XFapiAuthDate, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "x-fapi-auth-date", Err: err})
			return
		}

		params.XFapiAuthDate = &XFapiAuthDate

	}

	// ------------- Optional header parameter "x-fapi-customer-ip-address" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-fapi-customer-ip-address")]; found {
		var XFapiCustomerIPAddress XFapiCustomerIPAddress
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "x-fapi-customer-ip-address", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-fapi-customer-ip-address", valueList[0], &XFapiCustomerIPAddress, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "x-fapi-customer-ip-address", Err: err})
			return
		}

		params.XFapiCustomerIPAddress = &XFapiCustomerIPAddress

	}

	// ------------- Required header parameter "x-fapi-interaction-id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-fapi-interaction-id")]; found {
		var XFapiInteractionID XFapiInteractionID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "x-fapi-interaction-id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-fapi-interaction-id", valueList[0], &XFapiInteractionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "x-fapi-interaction-id", Err: err})
			return
		}

		params.XFapiInteractionID = XFapiInteractionID

	} else {
		err := fmt.Errorf("Header parameter x-fapi-interaction-id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "x-fapi-interaction-id", Err: err})
		return
	}

	// ------------- Optional header parameter "x-customer-user-agent" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-customer-user-agent")]; found {
		var XCustomerUserAgent XCustomerUserAgent
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "x-customer-user-agent", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-customer-user-agent", valueList[0], &XCustomerUserAgent, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "x-customer-user-agent", Err: err})
			return
		}

		params.XCustomerUserAgent = &XCustomerUserAgent

	}

	// ------------- Optional header parameter "x-v" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-v")]; found {
		var XVHeader XVHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "x-v", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-v", valueList[0], &XVHeader, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "x-v", Err: err})
			return
		}

		params.XVHeader = &XVHeader

	}

	// ------------- Optional header parameter "x-min-v" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-min-v")]; found {
		var XMinV XMinV
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "x-min-v", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-min-v", valueList[0], &XMinV, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "x-min-v", Err: err})
			return
		}

		params.XMinV = &XMinV

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetInsuranceFinancialAssistance(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetInsuranceFinancialAssistanceContractInfo operation middleware
func (siw *ServerInterfaceWrapper) GetInsuranceFinancialAssistanceContractInfo(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "contractId" -------------
	var contractID ContractID

	err = runtime.BindStyledParameterWithOptions("simple", "contractId", r.PathValue("contractId"), &contractID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "contractId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, OAuth2SecurityScopes, []string{"consent:consentId", "insurance-financial-assistance"})

	ctx = context.WithValue(ctx, OpenIdScopes, []string{"openid"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetInsuranceFinancialAssistanceContractInfoParams

	headers := r.Header

	// ------------- Required header parameter "Authorization" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authorization")]; found {
		var Authorization Authorization
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Authorization", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authorization", valueList[0], &Authorization, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Authorization", Err: err})
			return
		}

		params.Authorization = Authorization

	} else {
		err := fmt.Errorf("Header parameter Authorization is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Authorization", Err: err})
		return
	}

	// ------------- Optional header parameter "x-fapi-auth-date" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-fapi-auth-date")]; found {
		var XFapiAuthDate XFapiAuthDate
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "x-fapi-auth-date", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-fapi-auth-date", valueList[0], &XFapiAuthDate, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "x-fapi-auth-date", Err: err})
			return
		}

		params.XFapiAuthDate = &XFapiAuthDate

	}

	// ------------- Optional header parameter "x-fapi-customer-ip-address" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-fapi-customer-ip-address")]; found {
		var XFapiCustomerIPAddress XFapiCustomerIPAddress
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "x-fapi-customer-ip-address", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-fapi-customer-ip-address", valueList[0], &XFapiCustomerIPAddress, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "x-fapi-customer-ip-address", Err: err})
			return
		}

		params.XFapiCustomerIPAddress = &XFapiCustomerIPAddress

	}

	// ------------- Required header parameter "x-fapi-interaction-id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-fapi-interaction-id")]; found {
		var XFapiInteractionID XFapiInteractionID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "x-fapi-interaction-id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-fapi-interaction-id", valueList[0], &XFapiInteractionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "x-fapi-interaction-id", Err: err})
			return
		}

		params.XFapiInteractionID = XFapiInteractionID

	} else {
		err := fmt.Errorf("Header parameter x-fapi-interaction-id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "x-fapi-interaction-id", Err: err})
		return
	}

	// ------------- Optional header parameter "x-customer-user-agent" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-customer-user-agent")]; found {
		var XCustomerUserAgent XCustomerUserAgent
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "x-customer-user-agent", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-customer-user-agent", valueList[0], &XCustomerUserAgent, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "x-customer-user-agent", Err: err})
			return
		}

		params.XCustomerUserAgent = &XCustomerUserAgent

	}

	// ------------- Optional header parameter "x-v" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-v")]; found {
		var XVHeader XVHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "x-v", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-v", valueList[0], &XVHeader, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "x-v", Err: err})
			return
		}

		params.XVHeader = &XVHeader

	}

	// ------------- Optional header parameter "x-min-v" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-min-v")]; found {
		var XMinV XMinV
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "x-min-v", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-min-v", valueList[0], &XMinV, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "x-min-v", Err: err})
			return
		}

		params.XMinV = &XMinV

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetInsuranceFinancialAssistanceContractInfo(w, r, contractID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetInsuranceFinancialAssistanceMovements operation middleware
func (siw *ServerInterfaceWrapper) GetInsuranceFinancialAssistanceMovements(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "contractId" -------------
	var contractID ContractID

	err = runtime.BindStyledParameterWithOptions("simple", "contractId", r.PathValue("contractId"), &contractID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "contractId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, OAuth2SecurityScopes, []string{"consent:consentId", "insurance-financial-assistance"})

	ctx = context.WithValue(ctx, OpenIdScopes, []string{"openid"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetInsuranceFinancialAssistanceMovementsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "page-size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page-size", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page-size", Err: err})
		return
	}

	headers := r.Header

	// ------------- Required header parameter "Authorization" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Authorization")]; found {
		var Authorization Authorization
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Authorization", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Authorization", valueList[0], &Authorization, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Authorization", Err: err})
			return
		}

		params.Authorization = Authorization

	} else {
		err := fmt.Errorf("Header parameter Authorization is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Authorization", Err: err})
		return
	}

	// ------------- Optional header parameter "x-fapi-auth-date" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-fapi-auth-date")]; found {
		var XFapiAuthDate XFapiAuthDate
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "x-fapi-auth-date", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-fapi-auth-date", valueList[0], &XFapiAuthDate, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "x-fapi-auth-date", Err: err})
			return
		}

		params.XFapiAuthDate = &XFapiAuthDate

	}

	// ------------- Optional header parameter "x-fapi-customer-ip-address" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-fapi-customer-ip-address")]; found {
		var XFapiCustomerIPAddress XFapiCustomerIPAddress
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "x-fapi-customer-ip-address", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-fapi-customer-ip-address", valueList[0], &XFapiCustomerIPAddress, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "x-fapi-customer-ip-address", Err: err})
			return
		}

		params.XFapiCustomerIPAddress = &XFapiCustomerIPAddress

	}

	// ------------- Required header parameter "x-fapi-interaction-id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-fapi-interaction-id")]; found {
		var XFapiInteractionID XFapiInteractionID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "x-fapi-interaction-id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-fapi-interaction-id", valueList[0], &XFapiInteractionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "x-fapi-interaction-id", Err: err})
			return
		}

		params.XFapiInteractionID = XFapiInteractionID

	} else {
		err := fmt.Errorf("Header parameter x-fapi-interaction-id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "x-fapi-interaction-id", Err: err})
		return
	}

	// ------------- Optional header parameter "x-customer-user-agent" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-customer-user-agent")]; found {
		var XCustomerUserAgent XCustomerUserAgent
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "x-customer-user-agent", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-customer-user-agent", valueList[0], &XCustomerUserAgent, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "x-customer-user-agent", Err: err})
			return
		}

		params.XCustomerUserAgent = &XCustomerUserAgent

	}

	// ------------- Optional header parameter "x-v" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-v")]; found {
		var XVHeader XVHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "x-v", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-v", valueList[0], &XVHeader, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "x-v", Err: err})
			return
		}

		params.XVHeader = &XVHeader

	}

	// ------------- Optional header parameter "x-min-v" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-min-v")]; found {
		var XMinV XMinV
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "x-min-v", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-min-v", valueList[0], &XMinV, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "x-min-v", Err: err})
			return
		}

		params.XMinV = &XMinV

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetInsuranceFinancialAssistanceMovements(w, r, contractID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/insurance-financial-assistance/contracts", wrapper.GetInsuranceFinancialAssistance)
	m.HandleFunc("GET "+options.BaseURL+"/insurance-financial-assistance/{contractId}/contract-info", wrapper.GetInsuranceFinancialAssistanceContractInfo)
	m.HandleFunc("GET "+options.BaseURL+"/insurance-financial-assistance/{contractId}/movements", wrapper.GetInsuranceFinancialAssistanceMovements)

	return m
}

type BadRequestApplicationJSONCharsetUTF8Response ResponseError

type ForbiddenApplicationJSONCharsetUTF8Response ResponseError

type InternalServerErrorApplicationJSONCharsetUTF8Response ResponseError

type MethodNotAllowedApplicationJSONCharsetUTF8Response ResponseError

type NotAcceptableApplicationJSONCharsetUTF8Response ResponseError

type NotFoundApplicationJSONCharsetUTF8Response ResponseError

type OKResponseInsuranceFinancialAssistanceJSONResponse ResponseInsuranceFinancialAssistance

type OKResponseInsuranceFinancialAssistanceContractInfoJSONResponse ResponseInsuranceFinancialAssistanceContractInfo

type OKResponseInsuranceFinancialAssistanceMovementsJSONResponse ResponseInsuranceFinancialAssistanceMovements

type TooManyRequestsApplicationJSONCharsetUTF8Response ResponseError

type UnauthorizedApplicationJSONCharsetUTF8Response ResponseError

type UnprocessableEntityApplicationJSONCharsetUTF8Response ResponseError

type GetInsuranceFinancialAssistanceRequestObject struct {
	Params GetInsuranceFinancialAssistanceParams
}

type GetInsuranceFinancialAssistanceResponseObject interface {
	VisitGetInsuranceFinancialAssistanceResponse(w http.ResponseWriter) error
}

type GetInsuranceFinancialAssistance200JSONResponse struct {
	OKResponseInsuranceFinancialAssistanceJSONResponse
}

func (response GetInsuranceFinancialAssistance200JSONResponse) VisitGetInsuranceFinancialAssistanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetInsuranceFinancialAssistance400ApplicationJSONCharsetUTF8Response struct {
	BadRequestApplicationJSONCharsetUTF8Response
}

func (response GetInsuranceFinancialAssistance400ApplicationJSONCharsetUTF8Response) VisitGetInsuranceFinancialAssistanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetInsuranceFinancialAssistance401ApplicationJSONCharsetUTF8Response struct {
	UnauthorizedApplicationJSONCharsetUTF8Response
}

func (response GetInsuranceFinancialAssistance401ApplicationJSONCharsetUTF8Response) VisitGetInsuranceFinancialAssistanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetInsuranceFinancialAssistance403ApplicationJSONCharsetUTF8Response struct {
	ForbiddenApplicationJSONCharsetUTF8Response
}

func (response GetInsuranceFinancialAssistance403ApplicationJSONCharsetUTF8Response) VisitGetInsuranceFinancialAssistanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetInsuranceFinancialAssistance404ApplicationJSONCharsetUTF8Response struct {
	NotFoundApplicationJSONCharsetUTF8Response
}

func (response GetInsuranceFinancialAssistance404ApplicationJSONCharsetUTF8Response) VisitGetInsuranceFinancialAssistanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetInsuranceFinancialAssistance405ApplicationJSONCharsetUTF8Response struct {
	MethodNotAllowedApplicationJSONCharsetUTF8Response
}

func (response GetInsuranceFinancialAssistance405ApplicationJSONCharsetUTF8Response) VisitGetInsuranceFinancialAssistanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(405)

	return json.NewEncoder(w).Encode(response)
}

type GetInsuranceFinancialAssistance406ApplicationJSONCharsetUTF8Response struct {
	NotAcceptableApplicationJSONCharsetUTF8Response
}

func (response GetInsuranceFinancialAssistance406ApplicationJSONCharsetUTF8Response) VisitGetInsuranceFinancialAssistanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(406)

	return json.NewEncoder(w).Encode(response)
}

type GetInsuranceFinancialAssistance422ApplicationJSONCharsetUTF8Response struct {
	UnprocessableEntityApplicationJSONCharsetUTF8Response
}

func (response GetInsuranceFinancialAssistance422ApplicationJSONCharsetUTF8Response) VisitGetInsuranceFinancialAssistanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type GetInsuranceFinancialAssistance429ApplicationJSONCharsetUTF8Response struct {
	TooManyRequestsApplicationJSONCharsetUTF8Response
}

func (response GetInsuranceFinancialAssistance429ApplicationJSONCharsetUTF8Response) VisitGetInsuranceFinancialAssistanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response)
}

type GetInsuranceFinancialAssistance500ApplicationJSONCharsetUTF8Response struct {
	InternalServerErrorApplicationJSONCharsetUTF8Response
}

func (response GetInsuranceFinancialAssistance500ApplicationJSONCharsetUTF8Response) VisitGetInsuranceFinancialAssistanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetInsuranceFinancialAssistanceContractInfoRequestObject struct {
	ContractID ContractID `json:"contractId"`
	Params     GetInsuranceFinancialAssistanceContractInfoParams
}

type GetInsuranceFinancialAssistanceContractInfoResponseObject interface {
	VisitGetInsuranceFinancialAssistanceContractInfoResponse(w http.ResponseWriter) error
}

type GetInsuranceFinancialAssistanceContractInfo200JSONResponse struct {
	OKResponseInsuranceFinancialAssistanceContractInfoJSONResponse
}

func (response GetInsuranceFinancialAssistanceContractInfo200JSONResponse) VisitGetInsuranceFinancialAssistanceContractInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetInsuranceFinancialAssistanceContractInfo400ApplicationJSONCharsetUTF8Response struct {
	BadRequestApplicationJSONCharsetUTF8Response
}

func (response GetInsuranceFinancialAssistanceContractInfo400ApplicationJSONCharsetUTF8Response) VisitGetInsuranceFinancialAssistanceContractInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetInsuranceFinancialAssistanceContractInfo401ApplicationJSONCharsetUTF8Response struct {
	UnauthorizedApplicationJSONCharsetUTF8Response
}

func (response GetInsuranceFinancialAssistanceContractInfo401ApplicationJSONCharsetUTF8Response) VisitGetInsuranceFinancialAssistanceContractInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetInsuranceFinancialAssistanceContractInfo403ApplicationJSONCharsetUTF8Response struct {
	ForbiddenApplicationJSONCharsetUTF8Response
}

func (response GetInsuranceFinancialAssistanceContractInfo403ApplicationJSONCharsetUTF8Response) VisitGetInsuranceFinancialAssistanceContractInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetInsuranceFinancialAssistanceContractInfo404ApplicationJSONCharsetUTF8Response struct {
	NotFoundApplicationJSONCharsetUTF8Response
}

func (response GetInsuranceFinancialAssistanceContractInfo404ApplicationJSONCharsetUTF8Response) VisitGetInsuranceFinancialAssistanceContractInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetInsuranceFinancialAssistanceContractInfo405ApplicationJSONCharsetUTF8Response struct {
	MethodNotAllowedApplicationJSONCharsetUTF8Response
}

func (response GetInsuranceFinancialAssistanceContractInfo405ApplicationJSONCharsetUTF8Response) VisitGetInsuranceFinancialAssistanceContractInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(405)

	return json.NewEncoder(w).Encode(response)
}

type GetInsuranceFinancialAssistanceContractInfo406ApplicationJSONCharsetUTF8Response struct {
	NotAcceptableApplicationJSONCharsetUTF8Response
}

func (response GetInsuranceFinancialAssistanceContractInfo406ApplicationJSONCharsetUTF8Response) VisitGetInsuranceFinancialAssistanceContractInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(406)

	return json.NewEncoder(w).Encode(response)
}

type GetInsuranceFinancialAssistanceContractInfo422ApplicationJSONCharsetUTF8Response struct {
	UnprocessableEntityApplicationJSONCharsetUTF8Response
}

func (response GetInsuranceFinancialAssistanceContractInfo422ApplicationJSONCharsetUTF8Response) VisitGetInsuranceFinancialAssistanceContractInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type GetInsuranceFinancialAssistanceContractInfo429ApplicationJSONCharsetUTF8Response struct {
	TooManyRequestsApplicationJSONCharsetUTF8Response
}

func (response GetInsuranceFinancialAssistanceContractInfo429ApplicationJSONCharsetUTF8Response) VisitGetInsuranceFinancialAssistanceContractInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response)
}

type GetInsuranceFinancialAssistanceContractInfo500ApplicationJSONCharsetUTF8Response struct {
	InternalServerErrorApplicationJSONCharsetUTF8Response
}

func (response GetInsuranceFinancialAssistanceContractInfo500ApplicationJSONCharsetUTF8Response) VisitGetInsuranceFinancialAssistanceContractInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetInsuranceFinancialAssistanceMovementsRequestObject struct {
	ContractID ContractID `json:"contractId"`
	Params     GetInsuranceFinancialAssistanceMovementsParams
}

type GetInsuranceFinancialAssistanceMovementsResponseObject interface {
	VisitGetInsuranceFinancialAssistanceMovementsResponse(w http.ResponseWriter) error
}

type GetInsuranceFinancialAssistanceMovements200JSONResponse struct {
	OKResponseInsuranceFinancialAssistanceMovementsJSONResponse
}

func (response GetInsuranceFinancialAssistanceMovements200JSONResponse) VisitGetInsuranceFinancialAssistanceMovementsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetInsuranceFinancialAssistanceMovements400ApplicationJSONCharsetUTF8Response struct {
	BadRequestApplicationJSONCharsetUTF8Response
}

func (response GetInsuranceFinancialAssistanceMovements400ApplicationJSONCharsetUTF8Response) VisitGetInsuranceFinancialAssistanceMovementsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetInsuranceFinancialAssistanceMovements401ApplicationJSONCharsetUTF8Response struct {
	UnauthorizedApplicationJSONCharsetUTF8Response
}

func (response GetInsuranceFinancialAssistanceMovements401ApplicationJSONCharsetUTF8Response) VisitGetInsuranceFinancialAssistanceMovementsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetInsuranceFinancialAssistanceMovements403ApplicationJSONCharsetUTF8Response struct {
	ForbiddenApplicationJSONCharsetUTF8Response
}

func (response GetInsuranceFinancialAssistanceMovements403ApplicationJSONCharsetUTF8Response) VisitGetInsuranceFinancialAssistanceMovementsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetInsuranceFinancialAssistanceMovements404ApplicationJSONCharsetUTF8Response struct {
	NotFoundApplicationJSONCharsetUTF8Response
}

func (response GetInsuranceFinancialAssistanceMovements404ApplicationJSONCharsetUTF8Response) VisitGetInsuranceFinancialAssistanceMovementsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetInsuranceFinancialAssistanceMovements405ApplicationJSONCharsetUTF8Response struct {
	MethodNotAllowedApplicationJSONCharsetUTF8Response
}

func (response GetInsuranceFinancialAssistanceMovements405ApplicationJSONCharsetUTF8Response) VisitGetInsuranceFinancialAssistanceMovementsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(405)

	return json.NewEncoder(w).Encode(response)
}

type GetInsuranceFinancialAssistanceMovements406ApplicationJSONCharsetUTF8Response struct {
	NotAcceptableApplicationJSONCharsetUTF8Response
}

func (response GetInsuranceFinancialAssistanceMovements406ApplicationJSONCharsetUTF8Response) VisitGetInsuranceFinancialAssistanceMovementsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(406)

	return json.NewEncoder(w).Encode(response)
}

type GetInsuranceFinancialAssistanceMovements422ApplicationJSONCharsetUTF8Response struct {
	UnprocessableEntityApplicationJSONCharsetUTF8Response
}

func (response GetInsuranceFinancialAssistanceMovements422ApplicationJSONCharsetUTF8Response) VisitGetInsuranceFinancialAssistanceMovementsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(422)

	return json.NewEncoder(w).Encode(response)
}

type GetInsuranceFinancialAssistanceMovements429ApplicationJSONCharsetUTF8Response struct {
	TooManyRequestsApplicationJSONCharsetUTF8Response
}

func (response GetInsuranceFinancialAssistanceMovements429ApplicationJSONCharsetUTF8Response) VisitGetInsuranceFinancialAssistanceMovementsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response)
}

type GetInsuranceFinancialAssistanceMovements500ApplicationJSONCharsetUTF8Response struct {
	InternalServerErrorApplicationJSONCharsetUTF8Response
}

func (response GetInsuranceFinancialAssistanceMovements500ApplicationJSONCharsetUTF8Response) VisitGetInsuranceFinancialAssistanceMovementsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Obtem a lista de identificação de InsuranceFinancialAssistance
	// (GET /insurance-financial-assistance/contracts)
	GetInsuranceFinancialAssistance(ctx context.Context, request GetInsuranceFinancialAssistanceRequestObject) (GetInsuranceFinancialAssistanceResponseObject, error)
	// Obtém as informações gerais do contrato identificado por {contractId}
	// (GET /insurance-financial-assistance/{contractId}/contract-info)
	GetInsuranceFinancialAssistanceContractInfo(ctx context.Context, request GetInsuranceFinancialAssistanceContractInfoRequestObject) (GetInsuranceFinancialAssistanceContractInfoResponseObject, error)
	// Obtém os dados de movimentação do contrato identificado por {contractId}
	// (GET /insurance-financial-assistance/{contractId}/movements)
	GetInsuranceFinancialAssistanceMovements(ctx context.Context, request GetInsuranceFinancialAssistanceMovementsRequestObject) (GetInsuranceFinancialAssistanceMovementsResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetInsuranceFinancialAssistance operation middleware
func (sh *strictHandler) GetInsuranceFinancialAssistance(w http.ResponseWriter, r *http.Request, params GetInsuranceFinancialAssistanceParams) {
	var request GetInsuranceFinancialAssistanceRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetInsuranceFinancialAssistance(ctx, request.(GetInsuranceFinancialAssistanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetInsuranceFinancialAssistance")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetInsuranceFinancialAssistanceResponseObject); ok {
		if err := validResponse.VisitGetInsuranceFinancialAssistanceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetInsuranceFinancialAssistanceContractInfo operation middleware
func (sh *strictHandler) GetInsuranceFinancialAssistanceContractInfo(w http.ResponseWriter, r *http.Request, contractID ContractID, params GetInsuranceFinancialAssistanceContractInfoParams) {
	var request GetInsuranceFinancialAssistanceContractInfoRequestObject

	request.ContractID = contractID
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetInsuranceFinancialAssistanceContractInfo(ctx, request.(GetInsuranceFinancialAssistanceContractInfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetInsuranceFinancialAssistanceContractInfo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetInsuranceFinancialAssistanceContractInfoResponseObject); ok {
		if err := validResponse.VisitGetInsuranceFinancialAssistanceContractInfoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetInsuranceFinancialAssistanceMovements operation middleware
func (sh *strictHandler) GetInsuranceFinancialAssistanceMovements(w http.ResponseWriter, r *http.Request, contractID ContractID, params GetInsuranceFinancialAssistanceMovementsParams) {
	var request GetInsuranceFinancialAssistanceMovementsRequestObject

	request.ContractID = contractID
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetInsuranceFinancialAssistanceMovements(ctx, request.(GetInsuranceFinancialAssistanceMovementsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetInsuranceFinancialAssistanceMovements")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetInsuranceFinancialAssistanceMovementsResponseObject); ok {
		if err := validResponse.VisitGetInsuranceFinancialAssistanceMovementsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x8TW8jSZbYXwnkzKHUSFKUVNXdJcMwKIqSWCV+NJOsT2pWocwgFdWZEVkRkayPloD1",
	"zO7BB1/2uDbgaYzXvTV2eb07M7BnvIYB0/bJhzbgQ8/FWK9/gP+C8V5kJpNfEtVdNbXY6TpEUZERL95X",
	"vHjvxccXji+jWAomjHZ2v3BiqmjEDFP4VzUx51Lx19RwKaAiYNpXPLZ/OjV6xiZf0fBckqNer0NiGqjJ",
	"z2SZdJiKuGHkecII1cRXLGDC55RrotkzGpGhVIL5PKCaBCxmImAikCSQxPBYkoARxfxEaUm0DLnPDQ1k",
	"2XEdDqOeMxow5biOoBFzdueQdB3FnidcscDZNSphrqP9cxZRwD6iL4+ZGJlzZ3e7cvtT14mpMUwB0KeD",
	"wYvB4OFgoE8+clzHvIoBtDaKi5Fzeek6vhRGUd80gkU+NAImDB9ynwZSARW2sUFKqNZcm8nPgX4y5IIK",
	"n3FFM2pias6ntBRGWZOQjyvLsI3piC3i2Zr8JmJKkoCSePLliAuKEmLaTL4kGkWAY2pgOCW3JBnTECii",
	"JFY8ArTzjpM3ZGsjl8nzhKlXUzJw+CLCARvSJDTO7pbrDKWKqHF2HS7MzrbjOhEXPEoi/JiSwoVhI6Zy",
	"Wjz+egk9nyVUGB7QgBEjDQ2t4oy4NkpqEkuVYauvQrSkAfhSbLfvLEOXvkzRrVQq12L/shRxURovIv+A",
	"KT35mSTR5K3gEQW1YSKIJRcGGF7tNArCkCRmoSR+yJkwrEzaJGCGCYPqpklAoRyIgI2BAzqWImCK+DIi",
	"lIyzgWD60dBQopNYKhQxE0YxkuJI4Ne4TDxgJ0xNCjCx+6+Ynk5FqokAgEOpWDQFpl0C89ckIS1itQSn",
	"gUgi4k9+EfARThFtqEk0uV35mLSkIVXfZ7GhZyErD2BCs5c0ikNg7Ha5Uq6ssgMZp4uSXJwZL6+SxQ1l",
	"sILYgXgXIsgnHwDMPg+lInyU0JDIBKBJhTO40PZlaQxy8KemOeuLuGmmyACNE0U7FUlCE20JKsr9JlIf",
	"iDXlLr+l0LfKO6uFfqXAQd4jWUobP3pwZLtDfS3RRkZM9TVT1RETZoldFwH3KZEk0UyVKDRK2Z3oZPKl",
	"4pIkhof8NS2vxs9PxylNgTgrbPlWak/yv2+0Qr08oDGHxXCfmiXGcp8aSlg0T0AoRzIBzaZk8pvQgCUa",
	"s9epuBQDoUhVJl0WKwZ6AioLq5ovlVUgQsnT7kHtk+2drZNb58bEendz00gZ6jJnZliWarR5bqJwUw19",
	"aLRRJvWXLIpDuUu8RLhkq0I8FpPtytYnZOvu7u2d3Z0t0u/VVrN0SGNeook5LwVA6qol/u4MM+HPKTd/",
	"dKspxUUvYRcPWXDRO08uDhS/8Ki58BKx4ZLBIPhi+5LcukfFxQE7u2hSdVGN1UWTvrq4l4iLe0l4UU1G",
	"Fx6LL9q+uWjJ8cU+8zew4+3LtP/uzH/k1mGzd9Hv1TZ+uFqAmVo24moQKKb1oiTbYKSYYpOvJGl0wGjl",
	"0tS4mvMxU4SahIYRzGyQcTrbizK9hr+53vK4RFNU3p/eNoRh4PhwKZZ5WP2I9Bv7qGi3t7a3r1U0aLRB",
	"Ep0buSQijX1QXF8qxUI6+QodVY/lrqjE5UtRoSOuNRpTsOWOYrGSQfKaq4FDmNYstbVixsgGqa3Thl7H",
	"WD4ltcTX9vOu5PGPntLS62rpSaV092T6czAonXxRce/evVymb5cwMFhnzVDH9mjQZc8TptEQgiOa2kQa",
	"xyH30bvefKal+AfEP6dKM/MPEzMsfQpNphj/ULGhs+v8YHMaVmzar3qzmw5XV0oqi8GslKvZaovSIUPJ",
	"SURDdMAC6hIZccPBSaVG8bPESE3kmeIjaia/UFxqF4MLEExMX4WSBrBIUqPoePJGo9HK+wlK+t1jWAcO",
	"pDrjQcDEB6O6TYz8nAliWESY9mUsCReopkYCBUlESSzDyVsDixGsnGyUKComX1Fk0ZjLkAYUiMFZJGjo",
	"MTVmyo74wchCEgB9wpSSIJYRNewFfZW5VjKByoj7SmrN1JhPvpJARZOZcxm0pKmGoXzBgg8oGV8KnUQc",
	"wjp0txNCfaY1VdaQYogKZjWJSDR5Y2QgrZOUuUdID1CSezcfcHJlrpydXYAEF+cUcC8YMospCfiQKVw8",
	"wJeDqBxnUDR5G3BKYozvOXxCBQVgzxJhA16fgnVjiukiFEb6vYPSpyk/DmQiPqRcF9MLVm7sJdeGoWZm",
	"FoiDGxqh54PSbN/P4DeEhnnoswOM6jkNqxjrQ9U1tN2cmCsHW0LjfuqEk3UAEHlmpQm6rBNQ8RvQWsuS",
	"FmIof6d0zwz8XXlQBPbd+NGUY1QY/TtlxnTU78qJHNIqNvSkbFLxKnUX9Ac0aTJmik69BZjWGn2FWHJN",
	"ooQbqot2DyLaoVQ0IkOG3wIIv9FsJRHmVFTEhY311eQt2HOZEElCjvnMUSjPsjRT5qgASF/aBVsYhM8J",
	"NVyMuDUYfUHTDOUHXMpqM64qTQAD7qesSzMAm1yMJ1+G3BJtnZK8ylISK4nr31nI6sJw8+oD2nB0GWBl",
	"BtxFwMg0e4wYTX4TYKqTZTnCgM74ly5hhBLNhaEvFz5CGEVtsGCoS6Jp9oOTWGo9eTtmIcnYoQjVhAtt",
	"VJJqRBotM40hTkoVptQjmQizzwzl4ZLYDj6E5wznKsYZTG9a5YPoK1ag8IZbj50iqCXZLOhXHog0zEZY",
	"sWJM+Occ5jXmuXwaxXJ3IAai0+7W6q1e9bDe3CV3K+VP7wwEmfs3EM12q96rdhvtXfLx9p1KpfzxJ9C5",
	"3e91294u2apUKuRWOiIMKBOYVyCQXXIuFdUbmNYpRuA/urVVqQwG5cGgUrmAEHnL3b7EvyFa3vjhxY9u",
	"2dqPi39s3Sm2WRZKu04i+BK+dGZ4UAwdCAMfSMuc62Tg5AQPHMyacWEDEWkjvyiWZIAD9V7FbOAsSMeX",
	"AXoBTCSRs/vU+eYvyt/8meM61aHjOseO6/yvXzquc/+14zpAw3//E8d1vv7rr//d1/8Jfvzp1//ccZ2/",
	"+eoX8Md//PqvHNf55s/L3/yF4zp/++OfOa6zhzntLnTtwJ8QZ/6XP8PPXwLc//pPHdf5HGph4H8DX6Fb",
	"a/g5lJtVbAnV/+cnf4q/f+W4zr7jOp9BbxDVoeM6BwYGibHBz7H8NUD8tcXk//37v3ZcxzsHKP/in+Hn",
	"N3bA3/7EcZ3/+4d/gnVvHdf57R+Vf/tHAEvbP7A/NPxjIOPrX379K6T7Pnb4t47r9Jv4888d1/nfP4E2",
	"TfjWhdpmT+C3f+W4Tg0Y8M1flr/5NbTZ24TSw/Jvf/yXjuu8/m8/xt9/ZZv9Fv4KOPT/n39YTrsCj48Z",
	"kH+WIgc1f/Mf/jNg9scoiCjlI/Cg90OE+C+x/CWKghzgH//acZ0HwLEeoOq4zpP7zkkxldldqq0zWjqv",
	"tE3JAgrWqUOVz0LqzmXfGl67dHt76xMgJlO16kELFO0AhFw9PsYSuLf/BATc96Cs9wHB6j4oT92D8qAL",
	"VFTb2Kt9H0uE04aWj2rQq9r1sMQ23Q6Wj6FswteuhfkQNKfax/Y9bP8E4Txu4m8o9xCHvSMs94Fde3v4",
	"+3ELyz0sAdpevYblAZZAyx5S8aiNNThuo4Ute9i3jdOhjRDaD6Cs4ohVhP8QvraQur0uQutiyy6O0q1j",
	"iXC6CLOFvQ6x5vAeltj3EPv28XcDMKk9gL73j5BXVazBEe8/hrJ23MES61vAsRriWWv3oU0T6/ehbCF1",
	"NcTnqHsfS6zpY/s+1FdbwOHaY6x5Am1q3j0sUcr3sbwH0PZxlHrNwxK4UT+EGu8BwDn8DHCuI731OvTy",
	"ngBd9R7w5FEdcDu4j7pxD3A4aAAnH3UA8iFy/hAlcoh99/fh634dysMjD0sc5QggHDawRFoOe2BkDvew",
	"poXQWnUssddD/I2SOkTuHfWA3kYPxjpqYXkf6/vQt4FUN5ADjX3kP5YNlGDjM9SQOkBrHHtY2t/w9R5S",
	"ca8DErnXRnk9AW28X4eW9zsPoexi+RC/HkL9cfUeljDu8YNjLAHaMVJ07EHNkyrWeE38jW2Q9mOrD0eA",
	"+TFSdNyDEY9RssdI0XEf6psou+ZhFUuobz6EEZs4L5oPbAmcbKJeNRFas4e9un0s21DirHzURziPWlg+",
	"wBJb7mOvFuDQRI1t4mxtPqljiQYXbW8Lv7Y6AK11DBJpNdpYAuYtnCNNlEu7CW0697Gsgi51cNZ0HkOv",
	"Tr2F5RGWDSyBqx3Uk84xfj1+AmUPcPgMOdlFW9TFmdttH6O1Acjdh0C7h30fekCFh3bA6wEmnu2L1qaG",
	"pVeDGg+toneIlsQDXnk4a7wGQkBb5LUBKw9to7cPmHfRXtW9KpYw+jHS6O1je7SlHkrZ60J7D+dF7aiO",
	"5UMsgVceztwealTvnoclwOk9wd9HALnXgV491IEe0tJDW9RDe9tD29Vr9rAEGfUPH2HpYQlj9atHWCJd",
	"1jLXrf3HNh5wqf+4j2UDS+z12NbDuH3E50EftOVBfQ/LAyyxHvF50AKKHtcB/mPkw+O+LZtYArQnXVuC",
	"TJ80H2IJWD15iDPlYQ3LfSyx5UPU2D3g86ODNv5Gi4T2+dFeDUuU3QHg/whXmUePHqHtxZoOfu30sOZw",
	"dhW2hn9xI2Kah39qvbfZpfkk7yPPnjHfZI5mDyvn1+0ehiKUJMIGH4plqTCa7dZyoZniRYfSBgeFlbzg",
	"m6NFSF1SmGPoeBeQmvV+Aam2OU/P8czHglrmwdIUmcy9HaL72wb/XQ8c1+55WPzyLeQsnMh3lWaAuZlz",
	"LRWnuAVVntnRPYJ44FoR0IwZOZMXJJBu7+bHLnSimCrPhliFNiUexVIZe87JnDu7zoib8+Ss7MtoM0z4",
	"56/Gm5H0Py+lkDZ5mk/fTCsQx5ukwuYCNv95wg02vGKPNqDksyRP01aFYT6P8TzO84SKQJJzmYyZ2pjd",
	"JK9sb5Uqd0vbW07hyEq6PVoMuuz+5Ebp1tbTSmn75KLydKt092SjdGvnaWXr5OLp1vbJ00rpbv5h0WOd",
	"ZbrhEUsMD8t7ir7m4b4d8R2wPAOMPC9w7gENE2QdDcP20Nl9enUiYVYZLk/cZcHyegwnJWJb76nEYEKE",
	"BhEXXBtFDR+zA8b0e8EuoMRQxYeUzAyIWz40ksqkh986THEZLAt86WuMbatpY0tpIIlHw0CSfTZmmEiJ",
	"SMQ0ZhpyzbrtFnchdxbPOLmODxo+5D417OrTcfmweY8A0YqpMhx4LmzuvfiZi4CPeZAeeaHx5Bch91mh",
	"emYa3E4PaF1xOg6P8vmMj1lQUyzg5v2ITJKamrwJuMGdFp8FaQ7tPZwjvDH5CcyxhtCGhmGeqL6K5qtN",
	"3iI4GAV5y4Jj/jzhwXvh8fHkLcAGTsNY6f4MGw6ZD9OxJrXppmb23Qzboy/xnB4ejSBsyAwfS3v0EEd+",
	"GTOh35cNYGSf6ZhpqgkjdeFTNZJ6pYla0Txg5FmioF8kVbZvvgHID7l4f5g3k9Asrl+XrjNSMolra02J",
	"qfHIJkXRHtz6zMJOP+Z7nCHIiG7cfJbY9SjAqcENi77THGlYYAA3HYgqRV/ZcXCr9L1oaibsjCn2kEA2",
	"4vsSth2zRNo6/Zm7lpoIpk3mTOKJSMWiRLBcFQG/SApmqHrVj8F9eW86WTUJDfO1sAmDTr5UnF41pVb2",
	"yb17TSjxKR6YZjpVQ5dolkID+nSiWdyxOwetJDpjai21T/caJPGg/2w8EYdUyMJZ7jEXfhLC8nnzNWRr",
	"e+f2nTUmiKEv359wetlBnYz5+fnu/AsXPg8sy7U8U4zQwm7gkniucLB+1mFZKpGCAVjhMCxf4pYvr3PT",
	"fNkitdSTm+Hyandzfk4vi1RvuoQvOQyLszjd3wpoZlZyRcfqqb4tbIgMudLmqriHkTETfrZFVbhzMDfQ",
	"z+SS0OfO39fQJ6Q341p2incdpv29jRdjnD/cT3eo58Kh7GO6K7xMkws5mGa95WECd6/RrHu9Lv7udQt/",
	"fNav7hf/9urT39VWv3o8m3/KAS7Y1Od4oWUZzoWrLqsRvkHMNs4M9w3M9ZxJHae2p8jrAgluYcIXtPim",
	"tilzna6zRzI9FhnIzWI4uWCFAuknMFdWrbz76XdcL/niMuylo5BN0imGrVRr6XP4MPlp7pYuLqwff/Lp",
	"3a3KGstrhudV2UVGCtiuRK2gyrWO3YDq3MPMvOdVO+0uJtmn6cQpwrb1lZitSjGmwlEEEMtQTP2qoY1t",
	"MWNos4zLRrFnphdusMkIMwRd+hrk4QHLw2toz+m5l1BB7lMOflItnHyZBFySA7AeIsAJVJDJp5Xr0pMz",
	"AnLn9Sol4KbaPnN0bFZxQz5kHSY0eAfRHvWr+emPd+N72VRQId0SUNJp7tGada/GfJz6jbP+MTj6xZMU",
	"mhH0VYPEpKJmxJsBAB71PvNDqijJMlBrDEsleqwo7Wjyc1120M5bhoT0d80UxbUvvwUvutiPaaMSYzVW",
	"SLy0GOEh2RqNuZnGGOvyKmApQvNcclBrI8oFF6Mlft5na604bJmvR9HxQF2/ycqTY9MXMeXBd8CptogT",
	"ukIB5jzwuFZMR3gyy7CRSm/DlKGf5gFTVOWHfSoDJzNP2C+Vp796hBtSnWAwG+yzM27ej5JmSdwsRg0k",
	"KaUaE6SfBCUB+oySRHJsXcYFu7YE0zVV6EayXWYZZw/9AX+CgAORNOwUbOGQhprNr+sM+sxma27QOzus",
	"NbdRNr2tiFcYmI6ZP3k75P7MVdHZlWP7zp31rz+BKEGsyw4Cwl/W7QjZKD1vKBU5TyIqMJWnzSJec7jg",
	"LfeFMZU9uAv+WI9HK+8K4rk9sDF4CyI01IVfsLAzO2TBM+oe1Eo7Ozt3XWKDCUn6vVp5ScjxaWm70qt8",
	"urtT2a1UnswHHyXw4r9jBNK79Y924ctgEFxsP61sbe+cbOzaOvDAoH7h7ydrhy0509590GK4CZf5epO3",
	"Jgm/ixaARq613W0xyJVy2RyN6MuGnWBbO3ghLftrMbUZMYPnfIt8pDEvN6H+nbCPxjy7yTalJbUEVxmY",
	"625uzIUM1NKRG5bZz2eKiiXxSZMqnxLFsnveeHl8ZqcrkKQdM0FybMqkbTeLuJHEvs2gs5MDhJIIIbL/",
	"8Y8J3hTTqWOE98OUjJjWFINDCEQYLJKYGSMsxHu/9p4jU9heT94ozgoqQ2fux7nkjAk2nLz1uYS1NLud",
	"pUkiOBoATajU2V14PIo6b1CjmIr0jxWM80X8bFUYBjEKmJ6cFgIdwd8Azk1+apmxPL7CeT1rRPDo8O3L",
	"pccvLaqvWqsDjpvhUY/AYUDD2VYjKvJ8cfXaEGO6PXgl3z7wFuLq1OqyOTdrFRb6TnnvFhXiekirQsTf",
	"t3lXULxmp1v3qqRKvPphv4vH1wqSvFO5VpQilUM+eRfFMNfDGr91pBVy8blethwc44d3uB58sJUHF4qM",
	"0hSLb7sMXX2SKFuSvv2mffHm3PfCuaFwrkjTLDgL31ZEhft830+mlfK6dB3N/ERx88oDplohtKuJOd/2",
	"0g+La8RBmLyUBFsRMM5a2+czYqqs+af5MxmUGCbOqb33LdH62vdtBMUbX9wkaZRWeDuClklD+GHCSWHf",
	"Fg+BBlwxH2JSmxJduIpXfMxjbiWKSDY2mP1hKF/YKLf4/FktjWNnKvsqdHad7MUM+KTxfYByunRs0rkX",
	"1LQv49RzyxS0NMw0tEQLrrJTtw8WLDAxZdfkp6TaaaTrq1EytPfJs8hZF4MWTSZv8FqmJOPsjrnWXAqb",
	"6sP7iNeSgq1sNJUqCjTaxsu7MUvfFpH4qyaFYL5ZBFkGLT2j4vNyLP2yojzgNCpzuVl+wcKw9LmQL8Qm",
	"wOBBCQJiPkpUxrps1OIIVrd54XY09XGapO+CHMoxJqEnX9FF34TsKap56LhOMoPoixcvyiM5Lp+pTdy+",
	"dhZvx3YaeGah6PQd5E7fypFIiRxQzch2eTAYiJ6ir7MDHNlWC5s6lSxPJOW3a/MRNIlstg7mii5OFmhX",
	"nC32rTbNkoJnA4O3MIUntU440Wyk2CidJfbNrBhUjBJBTaJoSPKKZ4mavA24TxEI3lLGVJ6GiTa9AGlH",
	"supqJL5loMlprpqn5YEYiB+QtuJT8gaiSk67MmSnAAImc5rqnTvFqIliIcWJHlCYBdl9UHz4YvKGUHK6",
	"X91ve6eIY2cVDhjf06xTrNiYayMJcGDMs2vLp6j0p4WnTiSxb8+Q05nHEe1gdW1Y3idgY6YmX+J1V1VA",
	"GjPJszy7xQuxhXWrT9MWjeB0I5W2vNowTh8IcwnuCIXZYxKABcx6/TzhmhKwekYqIV0ACAywb1dpgydq",
	"0vfu0BIXsAb3uIhV0b4g8e3MfGum0N6ysQzHPDXoWaIL2B6w9KmsIrgig/ByMD5vRglNH8EosCu7Ss3S",
	"E/Lpe2en1X7vqN1tePV9K47JPyGGRmeTN9GMFbVjZ+9UFGgnt9CCuPkkdAkzfnkDRMieURJwwMlmiq4W",
	"xS2Z4Is5LtEsImfyecK4PSMIcsFZg3OLvaYpFfnzcDQxqFV2VmzOUK7JMxBl2iKQegPprIZAYgBjuwDi",
	"tGDgTwukU50qJaDLFNHAxOIrdGmePqDEV3zmWGCB+wVBpVYg/TsCHcG9Yq6uQcMuZEWlSHUHbwsHdDpR",
	"T0l64iub4tZ2/MA+hGqBL4UNen2VE4j3s6EpjpdEqPen4F4VbYNLqGUu4IYLsia3Tu0qfrqBG0a+RRyf",
	"N4nmiAZVy1mumSLyDFZVYPaupeMH5HQzz0ycDgQhpeL6vGsvjJfIYb23Sz766KDRqrZqjerxH1Q9r+H1",
	"qq1a/Q+69er+Rx9l0L6YZg0uc9AlWGi+Jfhau9XrVmu9RuugfdVYUeZWf8txmu0H9Wa91fPyQfK8qV1y",
	"V623pZUL+5gpbZfsrfJOuQIrOfgP4BXvOjvpk5coc3AaNq/2yTZnMkgjtuQefDN9qQh1UJ7BJKMkhP5L",
	"zzywKzXUQWSt/wPelXPIzDXti28Mr9j6mjbZnH3e99K9tsPsO4jrdlh8d2/dnrNP163Ta/HpyXV6lcbr",
	"NbOvoK7RFF/pXbMdPsB7eTL3Ztx2pbIqxM3bba75YNKl69xeB1zhnTrssnV9l5kXWLDTzvWdpg/DYY/b",
	"1/fI37XCDneu77Dw0Bl2/HitkQovikGv7e112LD4fAv2vXt93/knfy5d58460lr2Il0xaEcLMB+uY04Z",
	"1tLd3PXKDuSujkVPphHeU8dGZ84JaKxOooiqV86u0z6Dxe872TpDR2C1rjzE45wAhdfZ6dUr4I0Mt56L",
	"zkZMUT5/EPdGFnomN/i9tf67Yq0L2yzv0w7PZ4a/t8nf2+T3bJMhdFnDjpHZ/INUpGhC359tjorJ/nXt",
	"cuEZ9JkU2ewVtvJNbfN0U+B7w/ztDHPRjP7eO90ze0zfW/rvLf3vwNKvZxnfmbFHaoF6ayXnTs5mT0gG",
	"jHSUDJLsotTsXguNeVmmR3l8Ksu+jMpnCreASjlfrltTxls47VcjcCQjGcoRXYnD+btB4iRn3hdLX4nF",
	"HLFNlnJ9xQ7S9GH7q+P6k8v/HwAA//83dWDsZWoAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
